name: Resources Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - '#7-CI'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      TS_NODE_COMPILER: ttypescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm i
      - name: check
        run: cd ./package && npm run check

  compile:
    needs: [ check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RMG_BUILD_AND_RELEASE }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm i

      - name: Pre-publish
        run: |
          chmod +x ./prepublish.sh
          ./prepublish.sh

      - name: Pulish to npm
        if: github.ref == 'refs/heads/master'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RMG_NPM_PUBLISH }}