name: Resources Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      TS_NODE_COMPILER: ttypescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm run postinstall
      - name: check
        run: cd ./package && npm run check
