name: Resources Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - '#7-CI'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      TS_NODE_COMPILER: ttypescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm i
      - name: check
        run: npm run check

  compile:
    needs: [ check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm i

      - name: Bump version
        if: github.ref == 'refs/heads/master'
        run: npm version patch

      - name: build
        run: |
          npm run build

      - name: Pulish to npm
        if: github.ref == 'refs/heads/master'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrects.RMG_NPM_PUBLISH }}