name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '#7-CI'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TS_NODE_COMPILER: ttypescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm i
      - name: check
        run: node --loader ts-node/esm ./checker/check.ts
